name: next-aws-lambda

website:
  component: '@sls-next/serverless-component'
  inputs:
    bucketName: 'meemaw-next-aws-lambda-${env.PR_NAME}'
    memory:
      defaultLambda: 1024
      apiLambda: 1024
    cloudfront:
      comment: 'next-aws-lambda (Managed by @sls-next/serverless-component)'
